version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1-node-browsers
    working_directory: ~/app
    steps:
      - checkout
      - run: echo ${CIRCLE_PR_NUMBER}
      - run: sh ci-wcs.sh ${CIRCLE_BRANCH} ${CIRCLE_PR_NUMBER}
